// TaskFlow.Infrastructure/entities/User.cs
//
// WHAT: EF Core entity mapping onto the hand-authored `Users` table in TaskManagementDB.
// WHY:  This table was created manually in SSMS (see "Task Management Queries/SQLQuery4.sql" and
//       "SQLQuery5.sql" for the CREATE TABLE), not generated by EF migrations, so this class's
//       property names deliberately mirror the real SQL column names (UserId, CreatedDate, ...)
//       instead of EF's usual "Id"/"CreatedAt" conventions. Column mapping is finished off by
//       UserConfiguration (see configurations/UserConfigurations.cs) via ToTable/HasKey.
// WHERE USED: Read by UserRepository (Repositories/UserRepository.cs) during login to find the
//             account by email and load its roles. Hashed/verified against by
//             LoginCommandHandler (TaskFlow.Command/Auth/LoginCommand.cs). Every property read
//             there is used to build the JWT (JwtTokenGenerator) and the LoginResult DTO.

/// <summary>
/// A person who can sign in to TaskFlow. Maps 1:1 onto the <c>Users</c> table that already exists
/// in TaskManagementDB (created by hand in SSMS, not by EF migrations).
/// </summary>
public class User
{
    /// <summary>Primary key. Matches column <c>Users.UserId</c> (int identity).</summary>
    public int UserId { get; set; }

    /// <summary>Given name, shown in the UI (e.g. "Admin" in "Admin User"). Matches <c>Users.FirstName</c>.</summary>
    public string FirstName { get; set; } = string.Empty;

    /// <summary>Family name. Matches <c>Users.LastName</c>.</summary>
    public string LastName { get; set; } = string.Empty;

    /// <summary>Login identifier. Must be unique (enforced by a unique index in UserConfiguration) and matches <c>Users.Email</c>.</summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// ASP.NET Core Identity's <c>PasswordHasher&lt;User&gt;</c> output (PBKDF2, salted) — never a
    /// plaintext password. Verified in LoginCommandHandler via <c>IPasswordHasher&lt;User&gt;.VerifyHashedPassword</c>.
    /// Matches <c>Users.PasswordHash</c>.
    /// </summary>
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>Optional contact number. Matches <c>Users.PhoneNumber</c>. Not currently read by any login logic.</summary>
    public string? PhoneNumber { get; set; }

    /// <summary>Foreign key to <c>Departments.DepartmentId</c> — a real FK constraint already exists in the database (<c>FK_Users_Departments</c>). Nullable.</summary>
    public int? DepartmentId { get; set; }

    /// <summary>Navigation to the owning department, added in Phase 6 once <see cref="Department"/> exists as an entity.</summary>
    public Department? Department { get; set; }

    /// <summary>
    /// Soft-disable flag. LoginCommandHandler only allows sign-in when this is <c>true</c>
    /// (see the <c>u.IsActive</c> filter in its repository query). Matches <c>Users.IsActive</c>.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>Row creation timestamp. Matches <c>Users.CreatedDate</c>.</summary>
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    /// <summary>Last-modified timestamp, null until the row is first updated. Matches <c>Users.UpdatedDate</c>.</summary>
    public DateTime? UpdatedDate { get; set; }

    /// <summary>
    /// Join-table navigation to this user's roles (many-to-many via <see cref="UserRole"/>).
    /// UserRepository eagerly loads this (with <c>.Include(...).ThenInclude(...)</c>) so
    /// LoginCommandHandler can read role names without a second query.
    /// </summary>
    public ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}
