// TaskFlow.Infrastructure/TaskFlowDBContext.cs
//
// WHAT: The single EF Core DbContext for the whole backend.
// WHY:  One DbContext keeps all entities under one unit-of-work/change-tracker, which is what
//       lets Repository<T> and UserRepository share the same underlying connection/transaction
//       scope per request. Table/column mapping isn't done here — it's delegated to each entity's
//       IEntityTypeConfiguration (e.g. UserConfiguration) via ApplyConfigurationsFromAssembly, so
//       this file doesn't grow unwieldy as more features add entities.
// WHERE USED: Registered in Program.cs via `AddDbContext<TaskFlowDbContext>(...)` pointed at the
//             `TaskFlowDb` connection string (currently TaskManagementDB on .\SQLEXPRESS — an
//             existing, hand-authored database, not one created by EF migrations). Injected into
//             Repository<T> and UserRepository.
using Microsoft.EntityFrameworkCore;

/// <summary>
/// EF Core context for TaskManagementDB. Maps onto tables that were created by hand in SSMS (see
/// the "Task Management Queries" SQL scripts) rather than generated by EF migrations, so this
/// project intentionally does not run `dotnet ef database update` against it — schema changes are
/// made via SQL scripts, and this context/its configurations are kept in sync with them by hand.
/// </summary>
public class TaskFlowDbContext : DbContext
{
    /// <summary>Standard EF Core constructor — DbContextOptions (including the connection string) are supplied by DI via Program.cs.</summary>
    public TaskFlowDbContext(DbContextOptions<TaskFlowDbContext> options) : base(options) { }

    /// <summary>Query/write entry point for the <c>Users</c> table. Used by Repository&lt;User&gt;/UserRepository during login.</summary>
    public DbSet<User> Users => Set<User>();

    /// <summary>Query/write entry point for the <c>Roles</c> lookup table.</summary>
    public DbSet<Role> Roles => Set<Role>();

    /// <summary>Query/write entry point for the <c>UserRoles</c> join table.</summary>
    public DbSet<UserRole> UserRoles => Set<UserRole>();

    public DbSet<Project> Projects => Set<Project>();
    public DbSet<ProjectMember> ProjectMembers => Set<ProjectMember>();

    public DbSet<TaskItem> Tasks => Set<TaskItem>();
    public DbSet<TaskStatusLookup> TaskStatuses => Set<TaskStatusLookup>();
    public DbSet<TaskPriorityLookup> TaskPriorities => Set<TaskPriorityLookup>();
    public DbSet<Tag> Tags => Set<Tag>();
    public DbSet<TaskTag> TaskTags => Set<TaskTag>();
    public DbSet<TaskDependency> TaskDependencies => Set<TaskDependency>();

    public DbSet<Department> Departments => Set<Department>();

    public DbSet<TaskComment> TaskComments => Set<TaskComment>();
    public DbSet<TaskAttachment> TaskAttachments => Set<TaskAttachment>();

    public DbSet<TimeEntry> TimeEntries => Set<TimeEntry>();

    // further DbSet<T> properties are added feature by feature, starting in Phase 9

    /// <summary>
    /// Applies every <see cref="Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{TEntity}"/>
    /// found in this assembly (UserConfiguration, RoleConfiguration, UserRoleConfiguration, ...)
    /// instead of configuring each entity inline here, so adding a new feature's entity only means
    /// adding a new configuration class — this method never needs to change.
    /// </summary>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.ApplyConfigurationsFromAssembly(typeof(TaskFlowDbContext).Assembly);
}
