// TaskFlow.API/Program.cs
//
// WHAT: The composition root — wires every service registration, middleware, and route for the
//       whole backend into one ASP.NET Core pipeline.
// WHY:  This is the only place that should know about every layer at once (Infrastructure,
//       Command/Query handlers, AppServices, JWT config). Every other layer only knows about the
//       interfaces it depends on; this file is what actually binds each interface to its
//       concrete implementation via the DI container.
// WHERE USED: This is the application's entry point (implicit `Main`, generated by top-level
//             statements) — started by `dotnet run` and by the TaskFlow.API.http /
//             launchSettings.json profiles.
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();
// Enables attribute-routed MVC controllers (AuthController and future feature controllers) —
// without this, [ApiController] classes are never discovered and app.MapControllers() below has
// nothing to map.
builder.Services.AddControllers();

// The one EF Core DbContext for the app (TaskFlow.Infrastructure/TaskFlowDBContext.cs), pointed at
// the "TaskFlowDb" connection string in appsettings.Development.json — which currently targets
// TaskManagementDB on .\SQLEXPRESS, a database created by hand in SSMS, not by EF migrations.
builder.Services.AddDbContext<TaskFlowDbContext>(o =>
    o.UseSqlServer(builder.Configuration.GetConnectionString("TaskFlowDb")));

// Cross-cutting / Phase 1 pieces
// The hand-rolled Command/Query dispatcher (TaskFlow.Utility/Dispatcher.cs) — every AppServices
// class depends on this instead of a specific handler type.
builder.Services.AddScoped<Dispatcher>();

// Phase 2 — Login/Auth
// Each registration below binds an interface used somewhere up the call chain
// (AuthController -> IAuthService -> LoginCommandHandler) to its concrete implementation.
builder.Services.AddScoped<IUserRepository, UserRepository>();
// Singleton, not Scoped: JwtTokenGenerator only depends on IConfiguration (itself a singleton)
// and writes no instance state during GenerateToken, so one shared instance is thread-safe and
// avoids a per-request allocation. Revisit if it ever gains a scoped/transient dependency (e.g.
// a repository lookup) — that would make it a captive-dependency bug.
builder.Services.AddSingleton<IJwtTokenGenerator, JwtTokenGenerator>();
builder.Services.AddScoped<IPasswordHasher<User>, PasswordHasher<User>>();
builder.Services.AddScoped<IAuthService, AuthService>();
// The Dispatcher (above) resolves handlers by their IRequestHandler<TRequest, TResponse> type at
// runtime, so every Command/Query handler needs its own explicit registration like this one.
builder.Services.AddScoped<IRequestHandler<LoginCommand, LoginResult>, LoginCommandHandler>();

// Phase 3 — Projects
builder.Services.AddScoped<IProjectRepository, ProjectRepository>();
builder.Services.AddScoped<IRepository<ProjectMember>, Repository<ProjectMember>>();
builder.Services.AddScoped<IProjectService, ProjectService>();
builder.Services.AddScoped<IRequestHandler<GetProjectsQuery, List<ProjectDto>>, GetProjectsQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetProjectByIdQuery, ProjectDto>, GetProjectByIdQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetProjectMembersQuery, List<ProjectMemberDto>>, GetProjectMembersQueryHandler>();
builder.Services.AddScoped<IRequestHandler<CreateProjectCommand, int>, CreateProjectCommandHandler>();
builder.Services.AddScoped<IRequestHandler<UpdateProjectCommand>, UpdateProjectCommandHandler>();
builder.Services.AddScoped<IRequestHandler<DeleteProjectCommand>, DeleteProjectCommandHandler>();
builder.Services.AddScoped<IRequestHandler<AddProjectMemberCommand, int>, AddProjectMemberCommandHandler>();
builder.Services.AddScoped<IRequestHandler<RemoveProjectMemberCommand>, RemoveProjectMemberCommandHandler>();

// Phase 4 — Users (no new entity; management API over the Users table Phase 2 already maps)
builder.Services.AddScoped<IRepository<UserRole>, Repository<UserRole>>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<IRequestHandler<GetUsersQuery, List<UserDto>>, GetUsersQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetUserByIdQuery, UserDto>, GetUserByIdQueryHandler>();
builder.Services.AddScoped<IRequestHandler<CreateUserCommand, int>, CreateUserCommandHandler>();
builder.Services.AddScoped<IRequestHandler<UpdateUserCommand>, UpdateUserCommandHandler>();
builder.Services.AddScoped<IRequestHandler<SetUserActiveCommand>, SetUserActiveCommandHandler>();
builder.Services.AddScoped<IRequestHandler<UpdateUserRolesCommand>, UpdateUserRolesCommandHandler>();
builder.Services.AddScoped<IRepository<Role>, Repository<Role>>();
builder.Services.AddScoped<IRequestHandler<GetRolesQuery, List<RoleDto>>, GetRolesQueryHandler>();

// Phase 5 — Tasks
builder.Services.AddScoped<ITaskRepository, TaskRepository>();
builder.Services.AddScoped<IRepository<TaskStatusLookup>, Repository<TaskStatusLookup>>();
builder.Services.AddScoped<IRepository<TaskPriorityLookup>, Repository<TaskPriorityLookup>>();
builder.Services.AddScoped<IRepository<Tag>, Repository<Tag>>();
builder.Services.AddScoped<IRepository<TaskTag>, Repository<TaskTag>>();
builder.Services.AddScoped<IRepository<TaskDependency>, Repository<TaskDependency>>();
builder.Services.AddScoped<ITaskService, TaskService>();
builder.Services.AddScoped<IRequestHandler<GetTasksQuery, List<TaskItemDto>>, GetTasksQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetTaskByIdQuery, TaskItemDto>, GetTaskByIdQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetTaskDependenciesQuery, List<TaskDependencyDto>>, GetTaskDependenciesQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetTaskStatusesQuery, List<TaskStatusDto>>, GetTaskStatusesQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetTaskPrioritiesQuery, List<TaskPriorityDto>>, GetTaskPrioritiesQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetTagsQuery, List<TagDto>>, GetTagsQueryHandler>();
builder.Services.AddScoped<IRequestHandler<CreateTaskCommand, int>, CreateTaskCommandHandler>();
builder.Services.AddScoped<IRequestHandler<UpdateTaskCommand>, UpdateTaskCommandHandler>();
builder.Services.AddScoped<IRequestHandler<UpdateTaskStatusCommand>, UpdateTaskStatusCommandHandler>();
builder.Services.AddScoped<IRequestHandler<DeleteTaskCommand>, DeleteTaskCommandHandler>();
builder.Services.AddScoped<IRequestHandler<AddTaskTagCommand>, AddTaskTagCommandHandler>();
builder.Services.AddScoped<IRequestHandler<RemoveTaskTagCommand>, RemoveTaskTagCommandHandler>();
builder.Services.AddScoped<IRequestHandler<AddTaskDependencyCommand, int>, AddTaskDependencyCommandHandler>();
builder.Services.AddScoped<IRequestHandler<RemoveTaskDependencyCommand>, RemoveTaskDependencyCommandHandler>();

// Phase 6 — Departments
builder.Services.AddScoped<IRepository<Department>, Repository<Department>>();
builder.Services.AddScoped<IDepartmentService, DepartmentService>();
builder.Services.AddScoped<IRequestHandler<GetDepartmentsQuery, List<DepartmentDto>>, GetDepartmentsQueryHandler>();
builder.Services.AddScoped<IRequestHandler<CreateDepartmentCommand, int>, CreateDepartmentCommandHandler>();
builder.Services.AddScoped<IRequestHandler<UpdateDepartmentCommand>, UpdateDepartmentCommandHandler>();

// Phase 7 — Task comments & attachments
builder.Services.AddScoped<IRepository<TaskComment>, Repository<TaskComment>>();
builder.Services.AddScoped<IRepository<TaskAttachment>, Repository<TaskAttachment>>();
builder.Services.AddScoped<IRequestHandler<GetTaskCommentsQuery, List<TaskCommentDto>>, GetTaskCommentsQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetTaskAttachmentsQuery, List<TaskAttachmentDto>>, GetTaskAttachmentsQueryHandler>();
builder.Services.AddScoped<IRequestHandler<AddTaskCommentCommand, int>, AddTaskCommentCommandHandler>();
builder.Services.AddScoped<IRequestHandler<UpdateTaskCommentCommand>, UpdateTaskCommentCommandHandler>();
builder.Services.AddScoped<IRequestHandler<DeleteTaskCommentCommand>, DeleteTaskCommentCommandHandler>();
builder.Services.AddScoped<IRequestHandler<AddTaskAttachmentCommand, int>, AddTaskAttachmentCommandHandler>();
builder.Services.AddScoped<IRequestHandler<DeleteTaskAttachmentCommand>, DeleteTaskAttachmentCommandHandler>();

// Phase 8 — Time entries
builder.Services.AddScoped<IRepository<TimeEntry>, Repository<TimeEntry>>();
builder.Services.AddScoped<ITimeEntryService, TimeEntryService>();
builder.Services.AddScoped<IRequestHandler<GetTimeEntriesQuery, List<TimeEntryDto>>, GetTimeEntriesQueryHandler>();
builder.Services.AddScoped<IRequestHandler<LogTimeCommand, int>, LogTimeCommandHandler>();
builder.Services.AddScoped<IRequestHandler<DeleteTimeEntryCommand>, DeleteTimeEntryCommandHandler>();

// Phase 9 — Team & Dashboard (no new tables — pure aggregation queries over what already exists)
builder.Services.AddScoped<IDashboardService, DashboardService>();
builder.Services.AddScoped<ITeamService, TeamService>();
builder.Services.AddScoped<IRequestHandler<GetDashboardSummaryQuery, DashboardSummaryDto>, GetDashboardSummaryQueryHandler>();
builder.Services.AddScoped<IRequestHandler<GetTeamWorkloadQuery, List<TeamMemberWorkloadDto>>, GetTeamWorkloadQueryHandler>();

// Configures ASP.NET Core's JWT bearer authentication scheme to validate tokens produced by
// JwtTokenGenerator: same issuer/audience/signing key, read from the same "Jwt" config section.
// This is what makes [Authorize] (e.g. on AuthController.Me) actually check incoming tokens.
builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"],
            ValidateAudience = true,
            ValidAudience = builder.Configuration["Jwt:Audience"],
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"]!)),
            ValidateLifetime = true,
        };
    });
// Enables [Authorize]/[Authorize(Roles = "...")] attribute evaluation across all controllers.
builder.Services.AddAuthorization();

// The React frontend (Vite dev server) runs on a different origin (http://localhost:5173) than
// this API (http://localhost:5295), so the browser blocks cross-origin fetches unless the API
// explicitly allows that origin. This policy is what lets
// Frontend/src/services/api/authApi.ts's fetchBaseQuery call this API successfully.
const string FrontendCorsPolicy = "FrontendDev";
builder.Services.AddCors(options =>
{
    options.AddPolicy(FrontendCorsPolicy, policy =>
        policy.WithOrigins("http://localhost:5173")
              .AllowAnyHeader()
              .AllowAnyMethod());
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();

// Must run before auth/controllers so preflight (OPTIONS) requests and every actual response
// carry the Access-Control-Allow-* headers the browser checks.
app.UseCors(FrontendCorsPolicy);

// Wraps everything below in a try/catch that turns UnauthorizedException (thrown by
// LoginCommandHandler) into a clean HTTP 401 instead of an unhandled 500.
app.UseMiddleware<ExceptionHandlingMiddleware>();

app.UseAuthentication();
app.UseAuthorization();

// Maps every [ApiController]-attributed controller's routes (currently just AuthController).
app.MapControllers();

// --- Default template sample endpoint below (unrelated to Login/Auth) ---
var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast");

app.Run();

/// <summary>Leftover minimal-API sample record from the default WebAPI template; not part of Login/Auth. Backs the <c>/weatherforecast</c> endpoint above.</summary>
record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
